# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Nine Ghosts"
license = "MIT"
licenselink = "https://github.com/BB-Code/nine-ghosts/blob/master/LICENSE"
description = ""
homepage = "https://github.com/BB-Code/nine-ghosts.git"
tags = ["blog", "responsive", "concision", "dark", "light"]
features = []

[author]
  name = "BB-Code"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
